# Generated by Django 6.0.4 on 2026-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='competition_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('fresher', 'Fresher (0–1 yr)'), ('mid', 'Mid-level (2–5 yr)'), ('senior', 'Senior (5+ yr)')], default='mid', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='is_fresher_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_internship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='normalized_salary_inr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='source_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('adzuna', 'Adzuna'), ('jooble', 'Jooble'), ('naukri', 'Naukri'), ('internshala', 'Internshala'), ('foundit', 'Foundit (Monster)'), ('timesjobs', 'TimesJobs'), ('rss', 'RSS Feed'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='jobs_job_experie_09027f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_internship'], name='jobs_job_is_inte_8beb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_fresher_friendly'], name='jobs_job_is_fres_6534b2_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source_weight'], name='jobs_job_source__06e905_idx'),
        ),
    ]
